/**
 * Service Worker generated by PWA Studio Builder
 * App: Comércio do Bairro
 * Strategy: stale-while-revalidate
 */

const STATIC_CACHE_NAME = 'comrcio-do-b-cache-v1-static';
const RUNTIME_CACHE_NAME = 'comrcio-do-b-cache-v1-runtime';

const ALL_ASSETS = [
  "/",
  "/index.html",
  "/offline.html",
  "https://fonts.googleapis.com/icon?family=Material+Icons",
  "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap"
];

// Install Event
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(STATIC_CACHE_NAME).then((cache) => {
      console.log('[PWA SW] Pre-caching offline support files');
      return cache.addAll(ALL_ASSETS);
    }).then(() => self.skipWaiting())
  );
});

// Activate Event (Cache cleaning)
self.addEventListener('activate', (event) => {
  const cacheAllowlist = [STATIC_CACHE_NAME, RUNTIME_CACHE_NAME];
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheAllowlist.indexOf(cacheName) === -1) {
            console.log('[PWA SW] Clearing old cache:', cacheName);
            return caches.delete(cacheName);
          }
        })
      );
    }).then(() => self.clients.claim())
  );
});

// Fetch Event with "stale-while-revalidate" strategy
self.addEventListener('fetch', (event) => {
  // Safe-check that we only handle GET requests and local domains
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  
  // Skip browser extensions and non-HTTP requests
  if (!url.protocol.startsWith('http')) return;

  
    // Stale While Revalidate
    event.respondWith(
      caches.match(event.request).then((cachedResponse) => {
        const fetchPromise = fetch(event.request).then((networkResponse) => {
          if (networkResponse && networkResponse.status === 200) {
            const responseToCache = networkResponse.clone();
            caches.open(RUNTIME_CACHE_NAME).then((cache) => {
              cache.put(event.request, responseToCache);
            });
          }
          return networkResponse;
        }).catch(() => {
          // Fallback if network is shut
          if (event.request.mode === 'navigate' && !cachedResponse) {
            return caches.match('/offline.html');
          }
        });

        return cachedResponse || fetchPromise;
      })
    );
});
